name: Build Image Docker and Push Docker Hub

env:
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  DOCKER_HUB_USERNAME: "icarohenrique"

on:
  push:
    branches:
    - "publish"

jobs:
  build-push:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login Docker Hub
      run: docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_TOKEN
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm64/v8
        push: true
        tags: icarohenrique/cat-weather-bot:latest
